# Generated by Django 5.2.6 on 2026-06-03 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
