# Generated by Django 5.2.6 on 2026-07-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
