# Generated by Django 5.2.6 on 2026-07-12 16:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('other_interactions', '0001_initial'),
        ('posts', '0002_signals_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signals',
            new_name='Post',
        ),
    ]
